/******************************************************************************
* This file was generated by ZenStack CLI.
******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { Prisma, BlastShopifyStatistic } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateBlastShopifyStatistic(options?: Omit<(UseMutationOptions<(BlastShopifyStatistic | undefined), DefaultError, Prisma.BlastShopifyStatisticCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.BlastShopifyStatisticCreateArgs, DefaultError, BlastShopifyStatistic, true>('BlastShopifyStatistic', 'POST', `${endpoint}/blastShopifyStatistic/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.BlastShopifyStatisticCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.BlastShopifyStatisticCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, BlastShopifyStatistic, Prisma.BlastShopifyStatisticGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.BlastShopifyStatisticCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, BlastShopifyStatistic, Prisma.BlastShopifyStatisticGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyBlastShopifyStatistic(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.BlastShopifyStatisticCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.BlastShopifyStatisticCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('BlastShopifyStatistic', 'POST', `${endpoint}/blastShopifyStatistic/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.BlastShopifyStatisticCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.BlastShopifyStatisticCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.BlastShopifyStatisticCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyBlastShopifyStatistic<TArgs extends Prisma.BlastShopifyStatisticFindManyArgs, TQueryFnData = Array<Prisma.BlastShopifyStatisticGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.BlastShopifyStatisticFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('BlastShopifyStatistic', `${endpoint}/blastShopifyStatistic/findMany`, args, options, fetch);
}

export function useInfiniteFindManyBlastShopifyStatistic<TArgs extends Prisma.BlastShopifyStatisticFindManyArgs, TQueryFnData = Array<Prisma.BlastShopifyStatisticGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.BlastShopifyStatisticFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('BlastShopifyStatistic', `${endpoint}/blastShopifyStatistic/findMany`, args, options, fetch);
}

export function useSuspenseFindManyBlastShopifyStatistic<TArgs extends Prisma.BlastShopifyStatisticFindManyArgs, TQueryFnData = Array<Prisma.BlastShopifyStatisticGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.BlastShopifyStatisticFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('BlastShopifyStatistic', `${endpoint}/blastShopifyStatistic/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyBlastShopifyStatistic<TArgs extends Prisma.BlastShopifyStatisticFindManyArgs, TQueryFnData = Array<Prisma.BlastShopifyStatisticGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.BlastShopifyStatisticFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('BlastShopifyStatistic', `${endpoint}/blastShopifyStatistic/findMany`, args, options, fetch);
}

export function useFindUniqueBlastShopifyStatistic<TArgs extends Prisma.BlastShopifyStatisticFindUniqueArgs, TQueryFnData = Prisma.BlastShopifyStatisticGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.BlastShopifyStatisticFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('BlastShopifyStatistic', `${endpoint}/blastShopifyStatistic/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueBlastShopifyStatistic<TArgs extends Prisma.BlastShopifyStatisticFindUniqueArgs, TQueryFnData = Prisma.BlastShopifyStatisticGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.BlastShopifyStatisticFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('BlastShopifyStatistic', `${endpoint}/blastShopifyStatistic/findUnique`, args, options, fetch);
}

export function useFindFirstBlastShopifyStatistic<TArgs extends Prisma.BlastShopifyStatisticFindFirstArgs, TQueryFnData = Prisma.BlastShopifyStatisticGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.BlastShopifyStatisticFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('BlastShopifyStatistic', `${endpoint}/blastShopifyStatistic/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstBlastShopifyStatistic<TArgs extends Prisma.BlastShopifyStatisticFindFirstArgs, TQueryFnData = Prisma.BlastShopifyStatisticGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.BlastShopifyStatisticFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('BlastShopifyStatistic', `${endpoint}/blastShopifyStatistic/findFirst`, args, options, fetch);
}

export function useUpdateBlastShopifyStatistic(options?: Omit<(UseMutationOptions<(BlastShopifyStatistic | undefined), DefaultError, Prisma.BlastShopifyStatisticUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.BlastShopifyStatisticUpdateArgs, DefaultError, BlastShopifyStatistic, true>('BlastShopifyStatistic', 'PUT', `${endpoint}/blastShopifyStatistic/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.BlastShopifyStatisticUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.BlastShopifyStatisticUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, BlastShopifyStatistic, Prisma.BlastShopifyStatisticGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.BlastShopifyStatisticUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, BlastShopifyStatistic, Prisma.BlastShopifyStatisticGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyBlastShopifyStatistic(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.BlastShopifyStatisticUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.BlastShopifyStatisticUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('BlastShopifyStatistic', 'PUT', `${endpoint}/blastShopifyStatistic/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.BlastShopifyStatisticUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.BlastShopifyStatisticUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.BlastShopifyStatisticUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertBlastShopifyStatistic(options?: Omit<(UseMutationOptions<(BlastShopifyStatistic | undefined), DefaultError, Prisma.BlastShopifyStatisticUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.BlastShopifyStatisticUpsertArgs, DefaultError, BlastShopifyStatistic, true>('BlastShopifyStatistic', 'POST', `${endpoint}/blastShopifyStatistic/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.BlastShopifyStatisticUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.BlastShopifyStatisticUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, BlastShopifyStatistic, Prisma.BlastShopifyStatisticGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.BlastShopifyStatisticUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, BlastShopifyStatistic, Prisma.BlastShopifyStatisticGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteBlastShopifyStatistic(options?: Omit<(UseMutationOptions<(BlastShopifyStatistic | undefined), DefaultError, Prisma.BlastShopifyStatisticDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.BlastShopifyStatisticDeleteArgs, DefaultError, BlastShopifyStatistic, true>('BlastShopifyStatistic', 'DELETE', `${endpoint}/blastShopifyStatistic/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.BlastShopifyStatisticDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.BlastShopifyStatisticDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, BlastShopifyStatistic, Prisma.BlastShopifyStatisticGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.BlastShopifyStatisticDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, BlastShopifyStatistic, Prisma.BlastShopifyStatisticGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyBlastShopifyStatistic(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.BlastShopifyStatisticDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.BlastShopifyStatisticDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('BlastShopifyStatistic', 'DELETE', `${endpoint}/blastShopifyStatistic/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.BlastShopifyStatisticDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.BlastShopifyStatisticDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.BlastShopifyStatisticDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateBlastShopifyStatistic<TArgs extends Prisma.BlastShopifyStatisticAggregateArgs, TQueryFnData = Prisma.GetBlastShopifyStatisticAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.BlastShopifyStatisticAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('BlastShopifyStatistic', `${endpoint}/blastShopifyStatistic/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateBlastShopifyStatistic<TArgs extends Prisma.BlastShopifyStatisticAggregateArgs, TQueryFnData = Prisma.GetBlastShopifyStatisticAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.BlastShopifyStatisticAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('BlastShopifyStatistic', `${endpoint}/blastShopifyStatistic/aggregate`, args, options, fetch);
}

export function useGroupByBlastShopifyStatistic<TArgs extends Prisma.BlastShopifyStatisticGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.BlastShopifyStatisticGroupByArgs['orderBy'] } : { orderBy?: Prisma.BlastShopifyStatisticGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.BlastShopifyStatisticGroupByOutputType, TArgs['by']> &
        {
            [P in ((keyof TArgs) & (keyof Prisma.BlastShopifyStatisticGroupByOutputType))]: P extends '_count'
            ? TArgs[P] extends boolean
            ? number
            : Prisma.GetScalarType<TArgs[P], Prisma.BlastShopifyStatisticGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.BlastShopifyStatisticGroupByOutputType[P]>
        }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.BlastShopifyStatisticGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('BlastShopifyStatistic', `${endpoint}/blastShopifyStatistic/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByBlastShopifyStatistic<TArgs extends Prisma.BlastShopifyStatisticGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.BlastShopifyStatisticGroupByArgs['orderBy'] } : { orderBy?: Prisma.BlastShopifyStatisticGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.BlastShopifyStatisticGroupByOutputType, TArgs['by']> &
        {
            [P in ((keyof TArgs) & (keyof Prisma.BlastShopifyStatisticGroupByOutputType))]: P extends '_count'
            ? TArgs[P] extends boolean
            ? number
            : Prisma.GetScalarType<TArgs[P], Prisma.BlastShopifyStatisticGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.BlastShopifyStatisticGroupByOutputType[P]>
        }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.BlastShopifyStatisticGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('BlastShopifyStatistic', `${endpoint}/blastShopifyStatistic/groupBy`, args, options, fetch);
}

export function useCountBlastShopifyStatistic<TArgs extends Prisma.BlastShopifyStatisticCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.BlastShopifyStatisticCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.BlastShopifyStatisticCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('BlastShopifyStatistic', `${endpoint}/blastShopifyStatistic/count`, args, options, fetch);
}

export function useSuspenseCountBlastShopifyStatistic<TArgs extends Prisma.BlastShopifyStatisticCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.BlastShopifyStatisticCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.BlastShopifyStatisticCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('BlastShopifyStatistic', `${endpoint}/blastShopifyStatistic/count`, args, options, fetch);
}
import type { ActivityType } from '@prisma/client';

export function useCheckBlastShopifyStatistic<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; resourceId?: string; viewCount?: number; uniqueViewCount?: number; type?: ActivityType; blastId?: string }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('BlastShopifyStatistic', `${endpoint}/blastShopifyStatistic/check`, args, options, fetch);
}
