/******************************************************************************
* This file was generated by ZenStack CLI.
******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { Prisma, ContentSummary } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateContentSummary(options?: Omit<(UseMutationOptions<(ContentSummary | undefined), DefaultError, Prisma.ContentSummaryCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ContentSummaryCreateArgs, DefaultError, ContentSummary, true>('ContentSummary', 'POST', `${endpoint}/contentSummary/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ContentSummaryCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.ContentSummaryCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, ContentSummary, Prisma.ContentSummaryGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ContentSummaryCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, ContentSummary, Prisma.ContentSummaryGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyContentSummary(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.ContentSummaryCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ContentSummaryCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('ContentSummary', 'POST', `${endpoint}/contentSummary/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ContentSummaryCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.ContentSummaryCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.ContentSummaryCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyContentSummary<TArgs extends Prisma.ContentSummaryFindManyArgs, TQueryFnData = Array<Prisma.ContentSummaryGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ContentSummaryFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ContentSummary', `${endpoint}/contentSummary/findMany`, args, options, fetch);
}

export function useInfiniteFindManyContentSummary<TArgs extends Prisma.ContentSummaryFindManyArgs, TQueryFnData = Array<Prisma.ContentSummaryGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ContentSummaryFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('ContentSummary', `${endpoint}/contentSummary/findMany`, args, options, fetch);
}

export function useSuspenseFindManyContentSummary<TArgs extends Prisma.ContentSummaryFindManyArgs, TQueryFnData = Array<Prisma.ContentSummaryGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ContentSummaryFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ContentSummary', `${endpoint}/contentSummary/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyContentSummary<TArgs extends Prisma.ContentSummaryFindManyArgs, TQueryFnData = Array<Prisma.ContentSummaryGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ContentSummaryFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('ContentSummary', `${endpoint}/contentSummary/findMany`, args, options, fetch);
}

export function useFindUniqueContentSummary<TArgs extends Prisma.ContentSummaryFindUniqueArgs, TQueryFnData = Prisma.ContentSummaryGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.ContentSummaryFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ContentSummary', `${endpoint}/contentSummary/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueContentSummary<TArgs extends Prisma.ContentSummaryFindUniqueArgs, TQueryFnData = Prisma.ContentSummaryGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.ContentSummaryFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ContentSummary', `${endpoint}/contentSummary/findUnique`, args, options, fetch);
}

export function useFindFirstContentSummary<TArgs extends Prisma.ContentSummaryFindFirstArgs, TQueryFnData = Prisma.ContentSummaryGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ContentSummaryFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ContentSummary', `${endpoint}/contentSummary/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstContentSummary<TArgs extends Prisma.ContentSummaryFindFirstArgs, TQueryFnData = Prisma.ContentSummaryGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ContentSummaryFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ContentSummary', `${endpoint}/contentSummary/findFirst`, args, options, fetch);
}

export function useUpdateContentSummary(options?: Omit<(UseMutationOptions<(ContentSummary | undefined), DefaultError, Prisma.ContentSummaryUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ContentSummaryUpdateArgs, DefaultError, ContentSummary, true>('ContentSummary', 'PUT', `${endpoint}/contentSummary/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ContentSummaryUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.ContentSummaryUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, ContentSummary, Prisma.ContentSummaryGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ContentSummaryUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, ContentSummary, Prisma.ContentSummaryGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyContentSummary(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.ContentSummaryUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ContentSummaryUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('ContentSummary', 'PUT', `${endpoint}/contentSummary/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ContentSummaryUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.ContentSummaryUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.ContentSummaryUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertContentSummary(options?: Omit<(UseMutationOptions<(ContentSummary | undefined), DefaultError, Prisma.ContentSummaryUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ContentSummaryUpsertArgs, DefaultError, ContentSummary, true>('ContentSummary', 'POST', `${endpoint}/contentSummary/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ContentSummaryUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.ContentSummaryUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, ContentSummary, Prisma.ContentSummaryGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ContentSummaryUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, ContentSummary, Prisma.ContentSummaryGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteContentSummary(options?: Omit<(UseMutationOptions<(ContentSummary | undefined), DefaultError, Prisma.ContentSummaryDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ContentSummaryDeleteArgs, DefaultError, ContentSummary, true>('ContentSummary', 'DELETE', `${endpoint}/contentSummary/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ContentSummaryDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.ContentSummaryDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, ContentSummary, Prisma.ContentSummaryGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ContentSummaryDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, ContentSummary, Prisma.ContentSummaryGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyContentSummary(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.ContentSummaryDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ContentSummaryDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('ContentSummary', 'DELETE', `${endpoint}/contentSummary/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ContentSummaryDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.ContentSummaryDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.ContentSummaryDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateContentSummary<TArgs extends Prisma.ContentSummaryAggregateArgs, TQueryFnData = Prisma.GetContentSummaryAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.ContentSummaryAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ContentSummary', `${endpoint}/contentSummary/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateContentSummary<TArgs extends Prisma.ContentSummaryAggregateArgs, TQueryFnData = Prisma.GetContentSummaryAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.ContentSummaryAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ContentSummary', `${endpoint}/contentSummary/aggregate`, args, options, fetch);
}

export function useGroupByContentSummary<TArgs extends Prisma.ContentSummaryGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.ContentSummaryGroupByArgs['orderBy'] } : { orderBy?: Prisma.ContentSummaryGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.ContentSummaryGroupByOutputType, TArgs['by']> &
        {
            [P in ((keyof TArgs) & (keyof Prisma.ContentSummaryGroupByOutputType))]: P extends '_count'
            ? TArgs[P] extends boolean
            ? number
            : Prisma.GetScalarType<TArgs[P], Prisma.ContentSummaryGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.ContentSummaryGroupByOutputType[P]>
        }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.ContentSummaryGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ContentSummary', `${endpoint}/contentSummary/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByContentSummary<TArgs extends Prisma.ContentSummaryGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.ContentSummaryGroupByArgs['orderBy'] } : { orderBy?: Prisma.ContentSummaryGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.ContentSummaryGroupByOutputType, TArgs['by']> &
        {
            [P in ((keyof TArgs) & (keyof Prisma.ContentSummaryGroupByOutputType))]: P extends '_count'
            ? TArgs[P] extends boolean
            ? number
            : Prisma.GetScalarType<TArgs[P], Prisma.ContentSummaryGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.ContentSummaryGroupByOutputType[P]>
        }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.ContentSummaryGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ContentSummary', `${endpoint}/contentSummary/groupBy`, args, options, fetch);
}

export function useCountContentSummary<TArgs extends Prisma.ContentSummaryCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.ContentSummaryCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ContentSummaryCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ContentSummary', `${endpoint}/contentSummary/count`, args, options, fetch);
}

export function useSuspenseCountContentSummary<TArgs extends Prisma.ContentSummaryCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.ContentSummaryCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ContentSummaryCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ContentSummary', `${endpoint}/contentSummary/count`, args, options, fetch);
}
import type { SummaryStatus, Sentiment } from '@prisma/client';

export function useCheckContentSummary<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; contentId?: string; summary?: string; summaryStatus?: SummaryStatus; sentiment?: Sentiment; keyThemes?: string }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('ContentSummary', `${endpoint}/contentSummary/check`, args, options, fetch);
}
