/******************************************************************************
* This file was generated by ZenStack CLI.
******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { Prisma, IdentifiedProductContent } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateIdentifiedProductContent(options?: Omit<(UseMutationOptions<(IdentifiedProductContent | undefined), DefaultError, Prisma.IdentifiedProductContentCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.IdentifiedProductContentCreateArgs, DefaultError, IdentifiedProductContent, true>('IdentifiedProductContent', 'POST', `${endpoint}/identifiedProductContent/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.IdentifiedProductContentCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.IdentifiedProductContentCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, IdentifiedProductContent, Prisma.IdentifiedProductContentGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.IdentifiedProductContentCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, IdentifiedProductContent, Prisma.IdentifiedProductContentGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyIdentifiedProductContent(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.IdentifiedProductContentCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.IdentifiedProductContentCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('IdentifiedProductContent', 'POST', `${endpoint}/identifiedProductContent/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.IdentifiedProductContentCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.IdentifiedProductContentCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.IdentifiedProductContentCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyIdentifiedProductContent<TArgs extends Prisma.IdentifiedProductContentFindManyArgs, TQueryFnData = Array<Prisma.IdentifiedProductContentGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.IdentifiedProductContentFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('IdentifiedProductContent', `${endpoint}/identifiedProductContent/findMany`, args, options, fetch);
}

export function useInfiniteFindManyIdentifiedProductContent<TArgs extends Prisma.IdentifiedProductContentFindManyArgs, TQueryFnData = Array<Prisma.IdentifiedProductContentGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.IdentifiedProductContentFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('IdentifiedProductContent', `${endpoint}/identifiedProductContent/findMany`, args, options, fetch);
}

export function useSuspenseFindManyIdentifiedProductContent<TArgs extends Prisma.IdentifiedProductContentFindManyArgs, TQueryFnData = Array<Prisma.IdentifiedProductContentGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.IdentifiedProductContentFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('IdentifiedProductContent', `${endpoint}/identifiedProductContent/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyIdentifiedProductContent<TArgs extends Prisma.IdentifiedProductContentFindManyArgs, TQueryFnData = Array<Prisma.IdentifiedProductContentGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.IdentifiedProductContentFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('IdentifiedProductContent', `${endpoint}/identifiedProductContent/findMany`, args, options, fetch);
}

export function useFindUniqueIdentifiedProductContent<TArgs extends Prisma.IdentifiedProductContentFindUniqueArgs, TQueryFnData = Prisma.IdentifiedProductContentGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.IdentifiedProductContentFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('IdentifiedProductContent', `${endpoint}/identifiedProductContent/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueIdentifiedProductContent<TArgs extends Prisma.IdentifiedProductContentFindUniqueArgs, TQueryFnData = Prisma.IdentifiedProductContentGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.IdentifiedProductContentFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('IdentifiedProductContent', `${endpoint}/identifiedProductContent/findUnique`, args, options, fetch);
}

export function useFindFirstIdentifiedProductContent<TArgs extends Prisma.IdentifiedProductContentFindFirstArgs, TQueryFnData = Prisma.IdentifiedProductContentGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.IdentifiedProductContentFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('IdentifiedProductContent', `${endpoint}/identifiedProductContent/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstIdentifiedProductContent<TArgs extends Prisma.IdentifiedProductContentFindFirstArgs, TQueryFnData = Prisma.IdentifiedProductContentGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.IdentifiedProductContentFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('IdentifiedProductContent', `${endpoint}/identifiedProductContent/findFirst`, args, options, fetch);
}

export function useUpdateIdentifiedProductContent(options?: Omit<(UseMutationOptions<(IdentifiedProductContent | undefined), DefaultError, Prisma.IdentifiedProductContentUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.IdentifiedProductContentUpdateArgs, DefaultError, IdentifiedProductContent, true>('IdentifiedProductContent', 'PUT', `${endpoint}/identifiedProductContent/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.IdentifiedProductContentUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.IdentifiedProductContentUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, IdentifiedProductContent, Prisma.IdentifiedProductContentGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.IdentifiedProductContentUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, IdentifiedProductContent, Prisma.IdentifiedProductContentGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyIdentifiedProductContent(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.IdentifiedProductContentUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.IdentifiedProductContentUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('IdentifiedProductContent', 'PUT', `${endpoint}/identifiedProductContent/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.IdentifiedProductContentUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.IdentifiedProductContentUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.IdentifiedProductContentUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertIdentifiedProductContent(options?: Omit<(UseMutationOptions<(IdentifiedProductContent | undefined), DefaultError, Prisma.IdentifiedProductContentUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.IdentifiedProductContentUpsertArgs, DefaultError, IdentifiedProductContent, true>('IdentifiedProductContent', 'POST', `${endpoint}/identifiedProductContent/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.IdentifiedProductContentUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.IdentifiedProductContentUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, IdentifiedProductContent, Prisma.IdentifiedProductContentGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.IdentifiedProductContentUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, IdentifiedProductContent, Prisma.IdentifiedProductContentGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteIdentifiedProductContent(options?: Omit<(UseMutationOptions<(IdentifiedProductContent | undefined), DefaultError, Prisma.IdentifiedProductContentDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.IdentifiedProductContentDeleteArgs, DefaultError, IdentifiedProductContent, true>('IdentifiedProductContent', 'DELETE', `${endpoint}/identifiedProductContent/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.IdentifiedProductContentDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.IdentifiedProductContentDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, IdentifiedProductContent, Prisma.IdentifiedProductContentGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.IdentifiedProductContentDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, IdentifiedProductContent, Prisma.IdentifiedProductContentGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyIdentifiedProductContent(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.IdentifiedProductContentDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.IdentifiedProductContentDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('IdentifiedProductContent', 'DELETE', `${endpoint}/identifiedProductContent/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.IdentifiedProductContentDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.IdentifiedProductContentDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.IdentifiedProductContentDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateIdentifiedProductContent<TArgs extends Prisma.IdentifiedProductContentAggregateArgs, TQueryFnData = Prisma.GetIdentifiedProductContentAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.IdentifiedProductContentAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('IdentifiedProductContent', `${endpoint}/identifiedProductContent/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateIdentifiedProductContent<TArgs extends Prisma.IdentifiedProductContentAggregateArgs, TQueryFnData = Prisma.GetIdentifiedProductContentAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.IdentifiedProductContentAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('IdentifiedProductContent', `${endpoint}/identifiedProductContent/aggregate`, args, options, fetch);
}

export function useGroupByIdentifiedProductContent<TArgs extends Prisma.IdentifiedProductContentGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.IdentifiedProductContentGroupByArgs['orderBy'] } : { orderBy?: Prisma.IdentifiedProductContentGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.IdentifiedProductContentGroupByOutputType, TArgs['by']> &
        {
            [P in ((keyof TArgs) & (keyof Prisma.IdentifiedProductContentGroupByOutputType))]: P extends '_count'
            ? TArgs[P] extends boolean
            ? number
            : Prisma.GetScalarType<TArgs[P], Prisma.IdentifiedProductContentGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.IdentifiedProductContentGroupByOutputType[P]>
        }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.IdentifiedProductContentGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('IdentifiedProductContent', `${endpoint}/identifiedProductContent/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByIdentifiedProductContent<TArgs extends Prisma.IdentifiedProductContentGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.IdentifiedProductContentGroupByArgs['orderBy'] } : { orderBy?: Prisma.IdentifiedProductContentGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.IdentifiedProductContentGroupByOutputType, TArgs['by']> &
        {
            [P in ((keyof TArgs) & (keyof Prisma.IdentifiedProductContentGroupByOutputType))]: P extends '_count'
            ? TArgs[P] extends boolean
            ? number
            : Prisma.GetScalarType<TArgs[P], Prisma.IdentifiedProductContentGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.IdentifiedProductContentGroupByOutputType[P]>
        }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.IdentifiedProductContentGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('IdentifiedProductContent', `${endpoint}/identifiedProductContent/groupBy`, args, options, fetch);
}

export function useCountIdentifiedProductContent<TArgs extends Prisma.IdentifiedProductContentCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.IdentifiedProductContentCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.IdentifiedProductContentCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('IdentifiedProductContent', `${endpoint}/identifiedProductContent/count`, args, options, fetch);
}

export function useSuspenseCountIdentifiedProductContent<TArgs extends Prisma.IdentifiedProductContentCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.IdentifiedProductContentCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.IdentifiedProductContentCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('IdentifiedProductContent', `${endpoint}/identifiedProductContent/count`, args, options, fetch);
}

export function useCheckIdentifiedProductContent<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; contentId?: string; shopifyResourceId?: string }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('IdentifiedProductContent', `${endpoint}/identifiedProductContent/check`, args, options, fetch);
}
