/******************************************************************************
* This file was generated by ZenStack CLI.
******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { Prisma, JourneySessionV2 } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateJourneySessionV2(options?: Omit<(UseMutationOptions<(JourneySessionV2 | undefined), DefaultError, Prisma.JourneySessionV2CreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.JourneySessionV2CreateArgs, DefaultError, JourneySessionV2, true>('JourneySessionV2', 'POST', `${endpoint}/journeySessionV2/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.JourneySessionV2CreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.JourneySessionV2CreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, JourneySessionV2, Prisma.JourneySessionV2GetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.JourneySessionV2CreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, JourneySessionV2, Prisma.JourneySessionV2GetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyJourneySessionV2(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.JourneySessionV2CreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.JourneySessionV2CreateManyArgs, DefaultError, Prisma.BatchPayload, false>('JourneySessionV2', 'POST', `${endpoint}/journeySessionV2/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.JourneySessionV2CreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.JourneySessionV2CreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.JourneySessionV2CreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyJourneySessionV2<TArgs extends Prisma.JourneySessionV2FindManyArgs, TQueryFnData = Array<Prisma.JourneySessionV2GetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.JourneySessionV2FindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('JourneySessionV2', `${endpoint}/journeySessionV2/findMany`, args, options, fetch);
}

export function useInfiniteFindManyJourneySessionV2<TArgs extends Prisma.JourneySessionV2FindManyArgs, TQueryFnData = Array<Prisma.JourneySessionV2GetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.JourneySessionV2FindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('JourneySessionV2', `${endpoint}/journeySessionV2/findMany`, args, options, fetch);
}

export function useSuspenseFindManyJourneySessionV2<TArgs extends Prisma.JourneySessionV2FindManyArgs, TQueryFnData = Array<Prisma.JourneySessionV2GetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.JourneySessionV2FindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('JourneySessionV2', `${endpoint}/journeySessionV2/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyJourneySessionV2<TArgs extends Prisma.JourneySessionV2FindManyArgs, TQueryFnData = Array<Prisma.JourneySessionV2GetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.JourneySessionV2FindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('JourneySessionV2', `${endpoint}/journeySessionV2/findMany`, args, options, fetch);
}

export function useFindUniqueJourneySessionV2<TArgs extends Prisma.JourneySessionV2FindUniqueArgs, TQueryFnData = Prisma.JourneySessionV2GetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.JourneySessionV2FindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('JourneySessionV2', `${endpoint}/journeySessionV2/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueJourneySessionV2<TArgs extends Prisma.JourneySessionV2FindUniqueArgs, TQueryFnData = Prisma.JourneySessionV2GetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.JourneySessionV2FindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('JourneySessionV2', `${endpoint}/journeySessionV2/findUnique`, args, options, fetch);
}

export function useFindFirstJourneySessionV2<TArgs extends Prisma.JourneySessionV2FindFirstArgs, TQueryFnData = Prisma.JourneySessionV2GetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.JourneySessionV2FindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('JourneySessionV2', `${endpoint}/journeySessionV2/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstJourneySessionV2<TArgs extends Prisma.JourneySessionV2FindFirstArgs, TQueryFnData = Prisma.JourneySessionV2GetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.JourneySessionV2FindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('JourneySessionV2', `${endpoint}/journeySessionV2/findFirst`, args, options, fetch);
}

export function useUpdateJourneySessionV2(options?: Omit<(UseMutationOptions<(JourneySessionV2 | undefined), DefaultError, Prisma.JourneySessionV2UpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.JourneySessionV2UpdateArgs, DefaultError, JourneySessionV2, true>('JourneySessionV2', 'PUT', `${endpoint}/journeySessionV2/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.JourneySessionV2UpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.JourneySessionV2UpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, JourneySessionV2, Prisma.JourneySessionV2GetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.JourneySessionV2UpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, JourneySessionV2, Prisma.JourneySessionV2GetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyJourneySessionV2(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.JourneySessionV2UpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.JourneySessionV2UpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('JourneySessionV2', 'PUT', `${endpoint}/journeySessionV2/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.JourneySessionV2UpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.JourneySessionV2UpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.JourneySessionV2UpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertJourneySessionV2(options?: Omit<(UseMutationOptions<(JourneySessionV2 | undefined), DefaultError, Prisma.JourneySessionV2UpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.JourneySessionV2UpsertArgs, DefaultError, JourneySessionV2, true>('JourneySessionV2', 'POST', `${endpoint}/journeySessionV2/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.JourneySessionV2UpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.JourneySessionV2UpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, JourneySessionV2, Prisma.JourneySessionV2GetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.JourneySessionV2UpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, JourneySessionV2, Prisma.JourneySessionV2GetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteJourneySessionV2(options?: Omit<(UseMutationOptions<(JourneySessionV2 | undefined), DefaultError, Prisma.JourneySessionV2DeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.JourneySessionV2DeleteArgs, DefaultError, JourneySessionV2, true>('JourneySessionV2', 'DELETE', `${endpoint}/journeySessionV2/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.JourneySessionV2DeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.JourneySessionV2DeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, JourneySessionV2, Prisma.JourneySessionV2GetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.JourneySessionV2DeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, JourneySessionV2, Prisma.JourneySessionV2GetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyJourneySessionV2(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.JourneySessionV2DeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.JourneySessionV2DeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('JourneySessionV2', 'DELETE', `${endpoint}/journeySessionV2/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.JourneySessionV2DeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.JourneySessionV2DeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.JourneySessionV2DeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateJourneySessionV2<TArgs extends Prisma.JourneySessionV2AggregateArgs, TQueryFnData = Prisma.GetJourneySessionV2AggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.JourneySessionV2AggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('JourneySessionV2', `${endpoint}/journeySessionV2/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateJourneySessionV2<TArgs extends Prisma.JourneySessionV2AggregateArgs, TQueryFnData = Prisma.GetJourneySessionV2AggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.JourneySessionV2AggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('JourneySessionV2', `${endpoint}/journeySessionV2/aggregate`, args, options, fetch);
}

export function useGroupByJourneySessionV2<TArgs extends Prisma.JourneySessionV2GroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.JourneySessionV2GroupByArgs['orderBy'] } : { orderBy?: Prisma.JourneySessionV2GroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.JourneySessionV2GroupByOutputType, TArgs['by']> &
        {
            [P in ((keyof TArgs) & (keyof Prisma.JourneySessionV2GroupByOutputType))]: P extends '_count'
            ? TArgs[P] extends boolean
            ? number
            : Prisma.GetScalarType<TArgs[P], Prisma.JourneySessionV2GroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.JourneySessionV2GroupByOutputType[P]>
        }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.JourneySessionV2GroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('JourneySessionV2', `${endpoint}/journeySessionV2/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByJourneySessionV2<TArgs extends Prisma.JourneySessionV2GroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.JourneySessionV2GroupByArgs['orderBy'] } : { orderBy?: Prisma.JourneySessionV2GroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.JourneySessionV2GroupByOutputType, TArgs['by']> &
        {
            [P in ((keyof TArgs) & (keyof Prisma.JourneySessionV2GroupByOutputType))]: P extends '_count'
            ? TArgs[P] extends boolean
            ? number
            : Prisma.GetScalarType<TArgs[P], Prisma.JourneySessionV2GroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.JourneySessionV2GroupByOutputType[P]>
        }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.JourneySessionV2GroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('JourneySessionV2', `${endpoint}/journeySessionV2/groupBy`, args, options, fetch);
}

export function useCountJourneySessionV2<TArgs extends Prisma.JourneySessionV2CountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.JourneySessionV2CountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.JourneySessionV2CountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('JourneySessionV2', `${endpoint}/journeySessionV2/count`, args, options, fetch);
}

export function useSuspenseCountJourneySessionV2<TArgs extends Prisma.JourneySessionV2CountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.JourneySessionV2CountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.JourneySessionV2CountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('JourneySessionV2', `${endpoint}/journeySessionV2/count`, args, options, fetch);
}
import type { JourneySessionStatus, JourneyTriggerEntity } from '@prisma/client';

export function useCheckJourneySessionV2<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; isExecuting?: boolean; lastActionBlockExecutedId?: string; status?: JourneySessionStatus; journeyId?: string; conversationId?: string; communityMemberId?: string; delayedCommentId?: string; delayedMessageId?: string; validatedTriggerId?: string; triggerEntity?: JourneyTriggerEntity; triggerMessageId?: string; triggeredById?: string; triggerCommentId?: string }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('JourneySessionV2', `${endpoint}/journeySessionV2/check`, args, options, fetch);
}
