/******************************************************************************
* This file was generated by ZenStack CLI.
******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { Prisma, TrackedTopic } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateTrackedTopic(options?: Omit<(UseMutationOptions<(TrackedTopic | undefined), DefaultError, Prisma.TrackedTopicCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TrackedTopicCreateArgs, DefaultError, TrackedTopic, true>('TrackedTopic', 'POST', `${endpoint}/trackedTopic/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TrackedTopicCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.TrackedTopicCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, TrackedTopic, Prisma.TrackedTopicGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.TrackedTopicCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, TrackedTopic, Prisma.TrackedTopicGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyTrackedTopic(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.TrackedTopicCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TrackedTopicCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('TrackedTopic', 'POST', `${endpoint}/trackedTopic/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TrackedTopicCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.TrackedTopicCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.TrackedTopicCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyTrackedTopic<TArgs extends Prisma.TrackedTopicFindManyArgs, TQueryFnData = Array<Prisma.TrackedTopicGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TrackedTopicFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TrackedTopic', `${endpoint}/trackedTopic/findMany`, args, options, fetch);
}

export function useInfiniteFindManyTrackedTopic<TArgs extends Prisma.TrackedTopicFindManyArgs, TQueryFnData = Array<Prisma.TrackedTopicGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TrackedTopicFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('TrackedTopic', `${endpoint}/trackedTopic/findMany`, args, options, fetch);
}

export function useSuspenseFindManyTrackedTopic<TArgs extends Prisma.TrackedTopicFindManyArgs, TQueryFnData = Array<Prisma.TrackedTopicGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TrackedTopicFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TrackedTopic', `${endpoint}/trackedTopic/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyTrackedTopic<TArgs extends Prisma.TrackedTopicFindManyArgs, TQueryFnData = Array<Prisma.TrackedTopicGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TrackedTopicFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('TrackedTopic', `${endpoint}/trackedTopic/findMany`, args, options, fetch);
}

export function useFindUniqueTrackedTopic<TArgs extends Prisma.TrackedTopicFindUniqueArgs, TQueryFnData = Prisma.TrackedTopicGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.TrackedTopicFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TrackedTopic', `${endpoint}/trackedTopic/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueTrackedTopic<TArgs extends Prisma.TrackedTopicFindUniqueArgs, TQueryFnData = Prisma.TrackedTopicGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.TrackedTopicFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TrackedTopic', `${endpoint}/trackedTopic/findUnique`, args, options, fetch);
}

export function useFindFirstTrackedTopic<TArgs extends Prisma.TrackedTopicFindFirstArgs, TQueryFnData = Prisma.TrackedTopicGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TrackedTopicFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TrackedTopic', `${endpoint}/trackedTopic/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstTrackedTopic<TArgs extends Prisma.TrackedTopicFindFirstArgs, TQueryFnData = Prisma.TrackedTopicGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TrackedTopicFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TrackedTopic', `${endpoint}/trackedTopic/findFirst`, args, options, fetch);
}

export function useUpdateTrackedTopic(options?: Omit<(UseMutationOptions<(TrackedTopic | undefined), DefaultError, Prisma.TrackedTopicUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TrackedTopicUpdateArgs, DefaultError, TrackedTopic, true>('TrackedTopic', 'PUT', `${endpoint}/trackedTopic/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TrackedTopicUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.TrackedTopicUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, TrackedTopic, Prisma.TrackedTopicGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.TrackedTopicUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, TrackedTopic, Prisma.TrackedTopicGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyTrackedTopic(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.TrackedTopicUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TrackedTopicUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('TrackedTopic', 'PUT', `${endpoint}/trackedTopic/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TrackedTopicUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.TrackedTopicUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.TrackedTopicUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertTrackedTopic(options?: Omit<(UseMutationOptions<(TrackedTopic | undefined), DefaultError, Prisma.TrackedTopicUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TrackedTopicUpsertArgs, DefaultError, TrackedTopic, true>('TrackedTopic', 'POST', `${endpoint}/trackedTopic/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TrackedTopicUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.TrackedTopicUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, TrackedTopic, Prisma.TrackedTopicGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.TrackedTopicUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, TrackedTopic, Prisma.TrackedTopicGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteTrackedTopic(options?: Omit<(UseMutationOptions<(TrackedTopic | undefined), DefaultError, Prisma.TrackedTopicDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TrackedTopicDeleteArgs, DefaultError, TrackedTopic, true>('TrackedTopic', 'DELETE', `${endpoint}/trackedTopic/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TrackedTopicDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.TrackedTopicDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, TrackedTopic, Prisma.TrackedTopicGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.TrackedTopicDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, TrackedTopic, Prisma.TrackedTopicGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyTrackedTopic(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.TrackedTopicDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.TrackedTopicDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('TrackedTopic', 'DELETE', `${endpoint}/trackedTopic/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.TrackedTopicDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.TrackedTopicDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.TrackedTopicDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateTrackedTopic<TArgs extends Prisma.TrackedTopicAggregateArgs, TQueryFnData = Prisma.GetTrackedTopicAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.TrackedTopicAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TrackedTopic', `${endpoint}/trackedTopic/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateTrackedTopic<TArgs extends Prisma.TrackedTopicAggregateArgs, TQueryFnData = Prisma.GetTrackedTopicAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.TrackedTopicAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TrackedTopic', `${endpoint}/trackedTopic/aggregate`, args, options, fetch);
}

export function useGroupByTrackedTopic<TArgs extends Prisma.TrackedTopicGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.TrackedTopicGroupByArgs['orderBy'] } : { orderBy?: Prisma.TrackedTopicGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.TrackedTopicGroupByOutputType, TArgs['by']> &
        {
            [P in ((keyof TArgs) & (keyof Prisma.TrackedTopicGroupByOutputType))]: P extends '_count'
            ? TArgs[P] extends boolean
            ? number
            : Prisma.GetScalarType<TArgs[P], Prisma.TrackedTopicGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.TrackedTopicGroupByOutputType[P]>
        }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.TrackedTopicGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TrackedTopic', `${endpoint}/trackedTopic/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByTrackedTopic<TArgs extends Prisma.TrackedTopicGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.TrackedTopicGroupByArgs['orderBy'] } : { orderBy?: Prisma.TrackedTopicGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.TrackedTopicGroupByOutputType, TArgs['by']> &
        {
            [P in ((keyof TArgs) & (keyof Prisma.TrackedTopicGroupByOutputType))]: P extends '_count'
            ? TArgs[P] extends boolean
            ? number
            : Prisma.GetScalarType<TArgs[P], Prisma.TrackedTopicGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.TrackedTopicGroupByOutputType[P]>
        }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.TrackedTopicGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TrackedTopic', `${endpoint}/trackedTopic/groupBy`, args, options, fetch);
}

export function useCountTrackedTopic<TArgs extends Prisma.TrackedTopicCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.TrackedTopicCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TrackedTopicCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('TrackedTopic', `${endpoint}/trackedTopic/count`, args, options, fetch);
}

export function useSuspenseCountTrackedTopic<TArgs extends Prisma.TrackedTopicCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.TrackedTopicCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.TrackedTopicCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('TrackedTopic', `${endpoint}/trackedTopic/count`, args, options, fetch);
}

export function useCheckTrackedTopic<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; workspaceId?: string; title?: string; description?: string; examples?: string }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('TrackedTopic', `${endpoint}/trackedTopic/check`, args, options, fetch);
}
